<?php
class Controllers
{
    // Function to load the model class
    public function model($model)
    {
        // Include the model file, where the model's filename is generated by capitalizing the first letter of the model name
        require_once '../app/models/' . ucwords($model) . '_model.php';
        
        // Append 'Model' to the model name to match the class name convention
        $model .= '_Model';

        // Return a new instance of the model class
        return new $model;
    }

    // Function to load a view file and optionally pass data to it
    public function view($view, $data = [])
    {
        // Check if the view file exists in the 'views' directory
        if (file_exists('../app/views/' . $view . '.php')) {
            // If the view exists, include the file
            require_once('../app/views/' . $view . '.php');
        } else {
            // If the file does not exist, print a 'Not found' message
            echo 'Not found';
        }
    }
}
